name: C/C++ CI

on:
  push:  # only runs manually from Actions tab

env:
  BUILD_CONFIG: Release
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:
    name: Build (android)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up build environment (Android)
        run: |
          sudo apt-get install -y ninja-build
          vcpkg install boost-system boost-filesystem boost-program-options boost-icl boost-variant openssl zlib --triplet=arm64-android

      - uses: hendrikmuhs/ccache-action@v1.2

      - name: Restore Gradle Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/
            /usr/local/share/vcpkg/installed
            /usr/local/share/vcpkg/packages
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('android/**/*.xml') }}-${{ hashFiles('android/**.java') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('android/**/*.xml') }}-
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-
            ${{ runner.os }}-gradle-

      - name: Decode Android keystore
        env:
          KEYSTORE_ENCODED: ${{ secrets.KEYSTORE }}
        run: |
          if [ -n "$KEYSTORE_ENCODED" ]; then
            echo "$KEYSTORE_ENCODED" | base64 --decode > /home/runner/keystore.jks
          fi

      - name: Build Vita3K (Android)
        env:
          SIGNING_STORE_PATH: "/home/runner/keystore.jks"
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          JVM_OPTS: -Xmx6G
          VCPKG_ROOT: /usr/local/share/vcpkg
        run: |
          cp -r data android/assets
          cp -r lang android/assets
          cp -r vita3k/shaders-builtin android/assets
          export JAVA_HOME=$(echo $JAVA_HOME_17_X64)
          if [ -e "$SIGNING_STORE_PATH" ];
          then
            BUILD_TYPE=Release
          else
            BUILD_TYPE=Reldebug
          fi
          ./gradlew --stacktrace --configuration-cache --build-cache --parallel --configure-on-demand assemble${BUILD_TYPE}
          echo "APK_PATH=android/build/outputs/apk/${BUILD_TYPE,,}/android-${BUILD_TYPE,,}.apk" >> $GITHUB_ENV

      - name: Compute git short SHA
        shell: bash
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Upload artifact (Android apk)
        uses: actions/upload-artifact@v7
        with:
          name: vita3k-${{ env.GIT_SHORT_SHA }}-android
          path: ${{ env.APK_PATH }}
